# Generated by Django 5.1.3 on 2024-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0003_remove_subject_student_studentsubject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpa",
            name="course",
        ),
        migrations.RemoveField(
            model_name="gpa",
            name="grade",
        ),
        migrations.AddField(
            model_name="grade",
            name="semester",
            field=models.CharField(default=123123, max_length=20),
            preserve_default=False,
        ),
    ]
